server.port 8888
spring.cloud.config.server.git.url=https://github.com/Maheshwarinarnaware23/Config.repo
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/dev_db
spring.datasource.username=root
spring.datasource.password=root
